### ISSUE TITLE
Infografía de hilos en C#

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/infografia-de-hilos-Anthony4523#2]
![Hilos en C#](https://user-images.githubusercontent.com/73609728/118449163-751cee00-b6b8-11eb-849c-0ab1b31937be.png)

**Comment by CxrlosMX** [comment]
Excelente infografía compañero, cumple con la rubrica. 
Porcentaje obtenido: 20%

**Comment by josealfredo79** [comment]
Revisado y bien hecho.
